### ISSUE TITLE
Filter by price products with type selection issue

### ISSUE THREAD

**Issue by Tantacula** [aimeos/ai-controller-frontend#19]
I have product with type "selection" which has no price itself, but has variant with price $100. When I try to apply filtering by price this product doesn't display in results (I tried in default theme and using jsonapi).

**Comment by aimeos** [comment]
Each selection product needs the lowest price of all articles. Otherwise, it won't be found when sorting by price because there's none and therefore skipped.

**Comment by Tantacula** [comment]
Is it possible to fetch lowest price automatically during search request?

**Comment by aimeos** [comment]
That would be too slow and therefore, it must be done upfront.
One possibility would be to add/update the price for the selection product in the admin backend automatically .
