### ISSUE TITLE
New Tag 2022.10.8 missing on packagist

### ISSUE THREAD

**Issue by DanielSiepmann** [aimeos/ai-controller-frontend#20]
Hey, thanks for providing security updates.
We wanted to fix https://github.com/advisories/GHSA-m9gv-6p22-qgmj by updating our installation to 2022.10.8, but this doesn't show up on packagist yet.

I'm confused as the tag and commits are from last month, accordingly to GitHub web ui.

The error seems to exist for other tags and branches as well. Maybe there is something broken in auto updating packagist for this package?

**Comment by aimeos** [comment]
Thanks for the hint! You are right, packagist didn't create packages for the older versions. This has been enforced now.

**Comment by DanielSiepmann** [comment]
Thanks, all tags are now shown on packagist.
Thanks for the fast response and fix.
