### ISSUE TITLE
Possibility to pass prefilled password

### ISSUE THREAD

**Issue by mfcanovas** [aimeos/ai-controller-frontend#7]
https://github.com/aimeos/ai-controller-frontend/blob/e94e1d1aa9c06530bfb073ce0a4be297e9b6a0ad/controller/frontend/src/Controller/Frontend/Customer/Standard.php#L73

add() method receives an array with data to add to the customer item but if you specify the customer password, it's ignored. add() method calls to fromArray() without the possibility to set _private_ arg to true which is needed to set the password.

**Comment by aimeos** [comment]
What do you want to achieve? Create a new account (through FE or JSON API) or just update the password?

**Comment by mfcanovas** [comment]
Create a new account using a custom Laravel endpoint.

This is how I have solved it for now:

```
$customerData = $request->get('customer');
$customerController = Customer::add($customerData);
$item = $customerController->get();
$item->setPassword($request->get('password'));
$itemArr = $customerController->store()->get()->toArray();
```

**Comment by aimeos** [comment]
Yes, that is the preferred way. Otherwise, it's likely to overwrite the password with the already encrypted one
